### PR TITLE
Add a hash function for blists

### PR DESCRIPTION
**Pull request by james-d-mitchell**
This commit includes a special hash function for `IsBlistRep`, a method
for `ChooseHashFunction`, and some tests. 

This was requested by @egri-nagy.

### CODE REVIEW

**Comment by egri-nagy** [comment]
Just would like to emphasize that this code is critical for our large scale computations, and indeed Orb is its most natural home. Thanks!

**Comment by fingolfin** [comment]
We'll add this or something like it during the upcoming GAP days.

Any reason you are using such a comparatively bad hash function? Perhaps `HashKeyBag` is too slow?

**Comment by fingolfin** [comment]
After discussing this with @james-d-mitchell I think this is fine as it is (and even if there is a better way to hash this, we can simply add it later on).

Thank you!

**Comment by egri-nagy** [comment]
Thanks a lot!

The previous hashing function simply turned the blist into an integer list, quite a wasteful step. 

Sure, I'm happy to test new ways, large scale!

**Pull request merged**
